listener 1883
protocol mqtt
allow_anonymous false
password_file /mosquitto/config/password.txt
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
log_dest file /mosquitto/log/mosquitto.log
log_type all